### registeruser
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "salim",
    "email": "salim@gmail.com",
    "password": "salim123",
    "identity_type": "KTP",
    "identity_number": "777777777",
    "address": "Jalan mawar"
}

### getUser
GET  http://localhost:3000/api/v1/users

### getUserDetail
GET  http://localhost:3000/api/v1/users/39

### editUser
PUT  http://localhost:3000/api/v1/users/39
Content-Type: application/json

{
     "identity_type": "KTP",
      "identity_number" : "999999"
}

### deleteUser
DELETE http://localhost:3000/api/v1/users/44

##################################################################################################

### create account bank
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "bank_name":"MANDIRI",
    "bank_account_number":"820775",
    "balance":50000,
    "user_id": 43
}

### get all bank account
GET http://localhost:3000/api/v1/accounts

### get detail bank account
GET http://localhost:3000/api/v1/accounts/33

### delete bank account
DELETE  http://localhost:3000/api/v1/accounts/27


###################################################

### create transactions 
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "amount": 50,
    "source_account_id": 33,
    "destination_account_id": 32
}

### Get all Transaction
GET http://localhost:3000/api/v1/transactions

### Get detail Transaction
GET http://localhost:3000/api/v1/transactions/22


###################

###AUTH

### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "gendut",
    "email": "gendut@gmail.com",
    "password": "password123",
    "identity_type": "KTP",
    "identity_number": "123456789",
    "address": "Jalan pahlawan"
}

### login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "gendut@gmail.com",
    "password": "password123"
}

### login dengan token
GET http://localhost:3000/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDIsIm5hbWUiOiJnZW5kdXQiLCJlbWFpbCI6ImdlbmR1dEBnbWFpbC5jb20iLCJpYXQiOjE3MTM2MTIxMjR9.Mp6bzvVVyLr5CABvkOqgr2XsnmWUufazdcWTRUv4n_w
